# Generated by Django 6.1 on 2026-08-10 18:42

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models

# Status values were renamed when the three-state order became a six-state one.
# Existing rows carry the old vocabulary and would otherwise sit in a state the
# new state machine has no transitions out of — an order stuck forever.
OLD_TO_NEW_STATUS = {
    "Pending": "Placed",
    "Assigned": "Dispatched",
    # "Delivered" kept its name.
}


def give_every_order_a_token(apps, schema_editor):
    """Populate `tracking_token` one row at a time.

    Has to be per-row: the column is about to become unique, and the whole
    reason it was added without that constraint is that a column default is
    evaluated once for the entire table.
    """
    Order = apps.get_model("api", "Order")
    for order in Order.objects.filter(tracking_token__isnull=True).iterator():
        order.tracking_token = api.models.generate_tracking_token()
        order.save(update_fields=["tracking_token"])


def drop_tokens(apps, schema_editor):
    """Reverse of the above — clear the column so the field can be removed."""
    Order = apps.get_model("api", "Order")
    Order.objects.update(tracking_token=None)


def rename_statuses(apps, schema_editor):
    Order = apps.get_model("api", "Order")
    for old, new in OLD_TO_NEW_STATUS.items():
        Order.objects.filter(status=old).update(status=new)


def restore_statuses(apps, schema_editor):
    Order = apps.get_model("api", "Order")
    for old, new in OLD_TO_NEW_STATUS.items():
        Order.objects.filter(status=new).update(status=old)


def deduplicate_category_names(apps, schema_editor):
    """Make category names unique before the constraint is applied.

    `Category.name` is becoming unique because the storefront joins products to
    categories by name, and two rows called "Dairy" make that join ambiguous.
    Any existing duplicates are suffixed rather than deleted — a category may
    have children pointing at it, and silently dropping rows during a migration
    is how data disappears without anyone noticing.
    """
    Category = apps.get_model("api", "Category")
    seen: set[str] = set()
    for category in Category.objects.order_by("id").iterator():
        key = (category.name or "").strip().lower()
        if key not in seen:
            seen.add(key)
            continue
        suffix = 2
        while f"{key} ({suffix})" in seen:
            suffix += 1
        category.name = f"{category.name} ({suffix})"
        seen.add(f"{key} ({suffix})")
        category.save(update_fields=["name"])


def backfill_order_money(apps, schema_editor):
    """Give pre-existing orders the totals the new columns expect.

    Orders created before this migration have line items but no stored
    `items_total` / `grand_total`, so they would render as ₹0.00 everywhere.
    Fees are left at zero deliberately: charging a historical order a delivery
    fee it was never quoted would misstate what the customer actually paid.
    """
    Order = apps.get_model("api", "Order")
    OrderItem = apps.get_model("api", "OrderItem")

    for order in Order.objects.iterator():
        items = list(OrderItem.objects.filter(order_id=order.id))
        if not items:
            continue
        total = Decimal("0.00")
        for item in items:
            line = (item.price or Decimal("0.00")) * item.quantity
            item.line_total = line
            item.save(update_fields=["line_total"])
            total += line
        order.items_total = total
        order.grand_total = total
        order.save(update_fields=["items_total", "grand_total"])


def noop(apps, schema_editor):
    """Reverse for data backfills that have nothing meaningful to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_pin_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRejection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'order_rejections',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='items_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery')], default='cod', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='promised_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            # Added WITHOUT the unique constraint on purpose. A single AddField
            # with a callable default evaluates that callable once and writes
            # the same value to every existing row, so adding it as unique in
            # one step fails on any table with more than one order in it. The
            # column is populated per-row by `give_every_order_a_token` below,
            # and only then altered to unique.
            #
            # Added without `db_index` either, and that is load-bearing on
            # Postgres. An indexed CharField there gets two indexes: a plain
            # btree and a `..._like` one with varchar_pattern_ops. The
            # AlterField below creates the same pair for the unique constraint,
            # and the `_like` name is derived from the table and column, so it
            # collides:
            #     ProgrammingError: relation
            #     "orders_tracking_token_9b07b1af_like" already exists
            # SQLite has no such index, which is why this only ever appeared on
            # the first real Postgres migrate. The index is redundant anyway --
            # the unique constraint below is itself an index.
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        # Must run before the unique constraint below, or the ALTER fails on any
        # database that already has two categories with the same name.
        migrations.RunPython(deduplicate_category_names, noop),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Packing', 'Packing'), ('Ready', 'Ready for pickup'), ('Dispatched', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], db_index=True, default='Placed', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category'], name='product_store_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active', 'is_available'], name='user_dispatch_idx'),
        ),
        migrations.AddField(
            model_name='orderrejection',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='api.order'),
        ),
        migrations.AddField(
            model_name='orderrejection',
            name='rider',
            field=models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='orderrejection',
            index=models.Index(fields=['rider', 'order'], name='rejection_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderrejection',
            constraint=models.UniqueConstraint(fields=('order', 'rider'), name='unique_order_rejection'),
        ),

        # --- data migrations, after every column exists -------------------
        migrations.RunPython(rename_statuses, restore_statuses),
        migrations.RunPython(backfill_order_money, noop),

        # Fill the column row by row, and only then make it unique and
        # non-nullable. Doing this in one AddField would give every existing
        # order the same token — and any holder of one could then read all of
        # them.
        migrations.RunPython(give_every_order_a_token, drop_tokens),
        migrations.AlterField(
            model_name='order',
            name='tracking_token',
            field=models.CharField(
                db_index=True,
                default=api.models.generate_tracking_token,
                max_length=64,
                unique=True,
            ),
        ),
    ]
