"""Correct the `opens_at`/`closes_at` defaults from strings to `time` objects.

Schema-identical: Postgres stores `time without time zone` either way, and a
default is not written into the column at all — Django applies it in Python. So
this migration changes nothing about existing rows and nothing about the table.

It matters because Django does not run `to_python` on a field default, so the
string `"07:00"` survived into any `StoreSettings` built in memory rather than
loaded from the database. `within_hours()` then compared `str` to
`datetime.time` and raised `TypeError` — turning `StoreSettings.load()`'s
"create it rather than crash" fallback into a 500 on every `/api/store/config`
and every checkout, on precisely the database that was already in trouble.
"""

# Generated by Django 6.1 on 2026-08-21 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_store_settings_and_failed_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='closes_at',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='opens_at',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
