# Generated by Django 6.1 on 2026-08-24 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_idempotency_cash_and_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('', 'Unknown')], default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rider', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.user')),
            ],
            options={
                'db_table': 'rider_devices',
                'indexes': [models.Index(fields=['rider'], name='device_rider_idx')],
            },
        ),
    ]
