# Generated by Django 6.1 on 2026-09-04 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_live_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('', 'Unknown')], default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.customer')),
            ],
            options={
                'db_table': 'customer_devices',
                'indexes': [models.Index(fields=['customer'], name='device_customer_idx')],
            },
        ),
    ]
